#pragma once
#include <commands/command_clear.h>
#include <commands/command_echo.h>
#include <commands/command_help.h>
#include <commands/command_login.h>
#include <commands/command_reboot.h>
#include <commands/command_shutdown.h>
#include <commands/command_useradd.h>
#include <commands/command_whoami.h>
#include <commands/command_sysinfo.h>
#include <commands/command_ls.h>
#include <commands/command_mkdir.h>
#include <commands/command_cd.h>
#include <commands/command_format.h>
#include <commands/command_cat.h>
#include <commands/command_touch.h>
#include <commands/command_rm.h>
#include <commands/command_run_knt.h>
#include <commands/command_edit.h>
#include <commands/command_sudo.h>
#include <commands/command_allocpage.h>
#include <commands/command_proc.h>
#include <commands/command.h>
#include <commands/command_ping.h>
#include <commands/command_journal.h>